// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2bP9KSCBxjsQmvRlhxGnnRZ5BVOp9VEs',
    appId: '1:316655156515:web:31cae5d124290b6649a096',
    messagingSenderId: '316655156515',
    projectId: 'unitask-648bb',
    authDomain: 'unitask-648bb.firebaseapp.com',
    storageBucket: 'unitask-648bb.appspot.com',
    measurementId: 'G-3WTDBBM4FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyXVl3Odd5ng9IfoI5td9u8uNCk7IB6Xk',
    appId: '1:316655156515:android:3d75b22a1680446849a096',
    messagingSenderId: '316655156515',
    projectId: 'unitask-648bb',
    storageBucket: 'unitask-648bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtpFnLl01PWaO4YOxQcNe1--mOsXYGDew',
    appId: '1:316655156515:ios:cb411b54cf0f36c949a096',
    messagingSenderId: '316655156515',
    projectId: 'unitask-648bb',
    storageBucket: 'unitask-648bb.appspot.com',
    iosClientId: '316655156515-k4fsnc7nbqu83ei0g3bv1vi0t0kfrrbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventFit',
  );
}
